import { type FC } from 'react';
import { createPortal } from 'react-dom';
import { X } from 'lucide-react';
import './InfoModal.css';

export type InfoModalType = 'tos' | 'about' | 'privacy' | 'refund';

interface InfoModalProps {
  type: InfoModalType;
  onClose: () => void;
}

const TOS_CONTENT = (
  <>
    <p className="info-modal-updated">Last updated: March 2026</p>

    <h3>1. Acceptance and Scope</h3>
    <p>By using CloseClaw, you agree to these Terms. CloseClaw provides a gateway to AI services (via OpenClaw). Content is generated by third-party AI models (Anthropic, OpenAI, Google).</p>

    <h3>2. Payments and Subscriptions</h3>
    <p>We use Apple In-App Purchases (IAP) for iOS and Stripe for Web. Subscriptions auto-renew. You can manage or cancel subscriptions via App Store Settings (iOS) or your Dashboard (Web). Per Apple Guideline 3.1.2, subscriptions may include monthly credit allotments.</p>

    <h3>3. AI Credit Packs (Consumables)</h3>
    <p>One-time credit top-ups are consumables. Credits purchased through IAP do not expire. Subscriptions and Top-ups are non-refundable once provisioned.</p>

    <h3>4. AI Safety & Content</h3>
    <p>Per Apple Safety Guidelines, you must not use the Service to generate "Highly Offensive" or harmful content. We provide a <strong>Flag/Report</strong> mechanism in the chat interface. Reported content is reviewed for safety compliance, and repeat offenders will be terminated.</p>

    <h3>5. Termination</h3>
    <p>We may terminate access for safety violations or non-payment. Upon termination, your data and private infrastructure are purged according to our Data Retention policy.</p>

    <h3>6. Contact</h3>
    <p>Support: <a href="mailto:support@closeclaw.in">support@closeclaw.in</a>.</p>
  </>
);

const PRIVACY_CONTENT = (
  <>
    <p className="info-modal-updated">Last updated: March 2026</p>

    <h3>Data Collection</h3>
    <p>We collect your Apple ID, name, and email for account setup. We collect technical "Usage Metadata" (token usage, cost, timestamp) to manage your billing and credits across devices.</p>

    <h3>AI Conversation Privacy</h3>
    <p>Conversations occur on your private, isolated instance. We do not store or monitor your conversation history on our central servers. However, content reported via the "Flag" button is reviewed for safety compliance.</p>

    <h3>Data Usage</h3>
    <p>We do not sell your data. Data is used solely to provision your instance and calculate billing. AI model providers (e.g., Anthropic) receive your prompts to generate responses under their own privacy policies.</p>

    <h3>Data Retention & Deletion</h3>
    <p>Accounts and data are retained while active. You can request immediate account and data deletion at any time in the app settings or by emailing <a href="mailto:support@closeclaw.in">support@closeclaw.in</a>. Data is purged within 30 days of deletion.</p>

    <h3>Third-Party Disclosure</h3>
    <p>We share necessary data with payment processors (Apple/Stripe) and infrastructure providers (GCP) to provide the service. No data is shared for advertising purposes.</p>
  </>
);

const REFUND_CONTENT = (
  <>
    <p className="info-modal-updated">Last updated: February 2026</p>

    <h3>Subscription Policy</h3>
    <p>Due to the immediate cost of provisioning a dedicated OpenClaw instance on GCP and the upfront allocation of AI credits, all CloseClaw subscriptions are non-refundable. Once a subscription is started, your private instance is provisioned and resources are reserved exclusively for you.</p>
    <p>You may cancel your subscription at any time through the dashboard. Upon cancellation, your OpenClaw instance will remain active until the end of your current billing period, after which it will be decommissioned.</p>

    <h3>AI Credit Top-ups</h3>
    <p>One-time credit top-up packs ($50) are non-refundable as they are provisioned and made available for use immediately upon purchase.</p>

    <h3>Technical Issues</h3>
    <p>If you experience a persistent technical issue that prevents the use of the service, please reach out to <a href="mailto:support@closeclaw.in">support@closeclaw.in</a>. We handle these cases individually and may offer a pro-rated refund or account credit if we are unable to resolve the infrastructure issue within 48 hours.</p>
  </>
);

const ABOUT_CONTENT = (
  <>
    <div className="info-modal-about-hero">
      <img src="/logo.png" alt="CloseClaw" className="info-modal-logo" />
      <h2>CloseClaw</h2>
      <p className="info-modal-tagline">Managed OpenClaw deployment for everyone.</p>
    </div>

    <p>CloseClaw gives you a private OpenClaw instance — always on, completely isolated, and ready on Telegram, Discord, or Slack within 60 seconds. No Docker. No server setup. No maintenance.</p>

    <p>Most people who want a self-hosted AI assistant face hours of setup: renting servers, configuring firewalls, wiring up bots, and maintaining everything when it breaks. We eliminate all of that.</p>

    <h3>What makes it different</h3>
    <p>Your assistant runs on a dedicated virtual machine that belongs to you alone. It's never shared with other users. Conversations are private by design — they never pass through our servers. We handle provisioning, uptime, updates, and security so you don't have to.</p>

    <h3>The technology</h3>
    <p>CloseClaw is built on top of <a href="https://docs.openclaw.ai" target="_blank" rel="noopener noreferrer">OpenClaw</a>, an open-source AI framework that handles model routing, web browsing, and multi-channel integrations. Your OpenClaw instance can use Claude, GPT, Gemini, and more — automatically picking the right model for each task.</p>

    <h3>Get in touch</h3>
    <p>We're a small team that cares deeply about privacy and developer experience. Reach us at <a href="mailto:support@closeclaw.in">support@closeclaw.in</a> — we read every message.</p>
  </>
);

const MODAL_CONFIG: Record<InfoModalType, { title: string; content: React.ReactNode }> = {
  tos: { title: 'Terms of Service', content: TOS_CONTENT },
  privacy: { title: 'Privacy Policy', content: PRIVACY_CONTENT },
  refund: { title: 'Refund Policy', content: REFUND_CONTENT },
  about: { title: 'About CloseClaw', content: ABOUT_CONTENT },
};

export const InfoModal: FC<InfoModalProps> = ({ type, onClose }) => {
  const { title, content } = MODAL_CONFIG[type];

  const modal = (
    <div className="info-modal-overlay" onClick={onClose}>
      <div className="info-modal-card" onClick={(e) => e.stopPropagation()}>
        <div className="info-modal-header">
          <h2>{title}</h2>
          <button className="info-modal-close" onClick={onClose} aria-label="Close">
            <X size={20} />
          </button>
        </div>
        <div className="info-modal-body">
          {content}
        </div>
      </div>
    </div>
  );

  return createPortal(modal, document.body);
};
