import React from 'react';
import { NebulaBackground } from '../components/ui/NebulaBackground';
import { Header } from '../components/ui/Header';
import { Footer } from '../components/ui/Footer';
import { Card } from '../components/ui/Card';
import './LegalPage.css';

interface LegalPageProps {
  type: 'privacy' | 'terms';
}

export const LegalPage: React.FC<LegalPageProps> = ({ type }) => {
  const content = type === 'privacy' ? PRIVACY_CONTENT : TOS_CONTENT;
  const title = type === 'privacy' ? 'Privacy Policy' : 'Terms of Service';

  return (
    <div className="legal-page">
      <NebulaBackground />
      <Header />
      <main className="legal-content-wrapper">
        <Card className="legal-card shadow-2xl">
          <h1 className="legal-title">{title}</h1>
          <div className="legal-body">
            {content}
          </div>
        </Card>
      </main>
      <Footer setInfoModal={() => {}} onGetStarted={() => {}} />
    </div>
  );
};

const TOS_CONTENT = (
  <>
    <p className="info-modal-updated">Last updated: March 2026</p>

    <h3>1. Acceptance and Scope</h3>
    <p>By using CloseClaw, you agree to these Terms. CloseClaw provides a gateway to AI services (via OpenClaw). Content is generated by third-party AI models (Anthropic, OpenAI, Google).</p>

    <h3>2. Payments and Subscriptions</h3>
    <p>We use Apple In-App Purchases (IAP) for iOS and Stripe for Web. Subscriptions auto-renew. You can manage or cancel subscriptions via App Store Settings (iOS) or your Dashboard (Web). Per Apple Guideline 3.1.2, subscriptions may include monthly credit allotments.</p>

    <h3>3. AI Credit Packs (Consumables)</h3>
    <p>One-time credit top-ups are consumables. Credits purchased through IAP do not expire. Subscriptions and Top-ups are non-refundable once provisioned.</p>

    <h3>4. AI Safety & Content</h3>
    <p>Per Apple Safety Guidelines, you must not use the Service to generate "Highly Offensive" or harmful content. We provide a <strong>Flag/Report</strong> mechanism in the chat interface. Reported content is reviewed for safety compliance, and repeat offenders will be terminated.</p>

    <h3>5. Termination</h3>
    <p>We may terminate access for safety violations or non-payment. Upon termination, your data and private infrastructure are purged according to our Data Retention policy.</p>

    <h3>6. Contact</h3>
    <p>Support: <a href="mailto:support@closeclaw.in">support@closeclaw.in</a>.</p>
  </>
);

const PRIVACY_CONTENT = (
  <>
    <p className="info-modal-updated">Last updated: March 2026</p>

    <h3>Data Collection</h3>
    <p>We collect your Google/Apple ID, name, and email for account setup. We collect technical "Usage Metadata" (token usage, cost, timestamp) to manage your billing and credits across devices.</p>

    <h3>AI Conversation Privacy</h3>
    <p>Conversations occur on your private, isolated instance. We do not store or monitor your conversation history on our central servers. However, content reported via the "Flag" button is reviewed for safety compliance.</p>

    <h3>Data Usage</h3>
    <p>We do not sell your data. Data is used solely to provision your instance and calculate billing. AI model providers (e.g., Anthropic) receive your prompts to generate responses under their own privacy policies.</p>

    <h3>Data Retention & Deletion</h3>
    <p>Accounts and data are retained while active. You can request immediate account and data deletion at any time in the app settings or by emailing <a href="mailto:support@closeclaw.in">support@closeclaw.in</a>. Data is purged within 30 days of deletion.</p>

    <h3>Third-Party Disclosure</h3>
    <p>We share necessary data with payment processors (Apple/Stripe) and infrastructure providers (GCP) to provide the service. No data is shared for advertising purposes.</p>
  </>
);
